In [2]:
import numpy as np

In [12]:
# Write a Python program to print the NumPy version in your system.

import numpy as np
print(np.__version__)

1.21.5


In [32]:
# Write a Python program to reverse an array (first element becomes last).
a=np.array([[1,2,3],
            [4,5,6],
           [7,8,9]])
np.flip(a)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [26]:
# Write a Python program to convert a list and tuple into arrays.

def converttoarr(a:"list/Tuple"):
    arr1=np.array(a)
    return arr1

t1=1,2,3,4
print(converttoarr(t1))

l1=["a","b","c"]
print(converttoarr(l1))
    

[1 2 3 4]
['a' 'b' 'c']


In [7]:
# Write a Python program to find common values between two arrays.

def common_values(a:"array1",b:"array2"):
    reshaped_arry1= np.reshape(a,(a.size,))
    reshaped_arry2= np.reshape(b,(b.size,))

    print(np.intersect1d(a, b)) 


a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])
b=np.array([[5,22,35,4],
           [5,6,78,8],
           [9,10,111,12]])
print(a)
print(b)

print()
common_values(a,b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  5  22  35   4]
 [  5   6  78   8]
 [  9  10 111  12]]

[ 4  5  6  8  9 10 12]


In [3]:
# Write a Python program compare two arrays using numpy.

arr2=np.array([[1,2,3,4],
              [4,44,56,78]])
arr3=np.array([[9,2,5,4],
               [9,0,56,78]])
print("comparing 2 arrays:")
arr2==arr3

comparing 2 arrays:


array([[False,  True, False,  True],
       [False, False,  True,  True]])

In [44]:
# Write a Python program to change the dimension of an array.

def reshape_(a):
    print(f'original array {a}')
    print()
    print(f'original shape {a.shape}')
    z=np.reshape(a,(a.size,))
    print()
    print(f'new array{z}')
    print()
    print(f'changed shape{z.shape}')
    
arr=np.array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])    
reshape_(arr)

original array [[9 8 7]
 [6 5 4]
 [3 2 1]]

original shape (3, 3)

new array[9 8 7 6 5 4 3 2 1]

changed shape(9,)


In [46]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

a=np.linspace(1,100,100,dtype=np.int32)
b=np.where((a%3==0)|(a%5==0),a,0).sum()
b

2418

In [32]:
# Write a Python program to convert a NumPy array into Python list structure. 

arry=np.array([1,2,34,5])
a=arry.tolist()
print(a)
print(type(a))

[1, 2, 34, 5]
<class 'list'>


In [26]:
# Write a Python program to how to add an extra column to a numpy array.

arr=np.array([[1,2],
              [3,4]])

arr2=np.array([5,6])
newarry=np.insert(arr,2,arr2,axis=1)
newarry

array([[1, 2, 5],
       [3, 4, 6]])

In [110]:
# Write a Python program to check whether the numpy array is empty or not.
def isempty(array:"Give array as an entry"):
    if array.size<1:
        return f"array{array} is Empty"
    else:
        return f"array {array} is Not Empty"
    
arry=np.array([])    
isempty(arry)

'array[] is Empty'

In [36]:
# How to ignore all numpy warnings (not recommended)?

np.seterr(all="ignore")
ArrayOf1 = np.array([1])
ArrayOf0 = np.array([0])
Output = ArrayOf1 / ArrayOf0
print(Output)

[inf]


In [30]:
# How to swap two rows of an array?

a=np.array([[1,2,3],
            [4,5,6]])

swap_rows=np.stack([a[-1],a[0]],axis=0)
swap_rows

array([[4, 5, 6],
       [1, 2, 3]])

In [31]:
# Python program to create a random vector of size 10 and sort it.

def sortedrandvec():
    randvec=np.random.randint(1,100,(10,))
    sortedvec=np.sort(randvec)
    return sortedvec

#only call the function to get a sorted random vector 1d-Array

sortedrandvec()

array([38, 44, 55, 64, 65, 68, 75, 85, 93, 94])

In [19]:
# Write a Python program to check two random arrays are equal or not.
import numpy as np
x = np.random.randint(0,2,(6,))
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 0 1 0 0]
Second array:
[1 0 1 0 0 0]
Test above two arrays are equal or not!
False


In [10]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise.

def computeele(arry:"Give an array",int1: "Give an num in int format for operation"):
    
    add=arry+int1
    print(add)

    sub=arry-int1
    print(sub)

    mul=arry*int1
    print(mul)

    div=arry/int1
    print(div)

arr=np.array([4,2]) #calling the function compele
int1=2
computeele(arr,int1)

[6 4]
[2 0]
[8 4]
[2. 1.]


In [61]:
# Write a Python program to get the dates of yesterday, today and tomorrow.

tod=np.datetime64("today","D")
print(tod)

tom=np.datetime64("today","D")+1
print(tom)

yes=np.datetime64("today","D")-1
print(yes)

2022-12-12
2022-12-13
2022-12-11
